### ISSUE TITLE
Recent Changes Don't Work With IDM 6.5

### ISSUE THREAD

**Issue by calleggr** [ForgeRock/end-user-ui#26]
Are the recent changes targeting IDM 7.0?

We pulled the latest code into our IDM 6.5 environment and our IDM<->AM integration stopped working. (it no longer redirects, and if you manually authenticate in AM, IDM freezes)
It was working previously using code from early April.

**Comment by jsonisathingy** [comment]
Yes, current master is focused on IDM 7.0. We recently stripped out AM support for the IDM enduser because we will be releasing a platform focused Login / Enduser for AM/IDM integration. Until its release I would recommend sticking to the 6.5.0.X as these are sustaining releases with various fixes and improvements.

**Comment by calleggr** [comment]
Got it. Thanks!
